services:
  - type: web
    name: medication-adherence-api
    env: python
    buildCommand: ""
    startCommand: "python random_forest_api.py"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
